### ISSUE TITLE
Broken in 11.0.1

### ISSUE THREAD

**Issue by DarkValkirion** [HamletDuFromage/aio-switch-updater#26] opened 2020-12-19 02:50 UTC
in version 11.0.1 it stays on a black screen and then throws an error. I used the latest version 1.3.1

**Comment by HamletDuFromage** [comment] 2020-12-19 02:58
Works for though, latest ams and 11.0.1
What cfw are you using? Are you launching it in applet mode or through title redirection?

**Comment by DarkValkirion** [comment] 2020-12-19 03:01
atmosphere M.16.1
In both ways of launching homebrew menu crashes when opening aio-switch-updater

**Comment by HamletDuFromage** [comment] 2020-12-19 03:03
Ah that's odd, i have the exact same setup. What kind of crash is it? The "an error occurred"? 
Can you try running it in airplane mode to see if it has something to do with fetching the links?

**Comment by DarkValkirion** [comment] 2020-12-19 03:13
In applet mode I get the atmosphere error screen but in title redirection it shows me the "an error occurred" screen.
I tried to run it now in airplane mode as you told me and it starts correctly but now it takes a longer time to load (approximately 30-35 seconds), now it no longer shows the error. Is it a cache problem or something similar? It's strange.

**Comment by HamletDuFromage** [comment] 2020-12-19 03:17
I'm not sure, but it's more than likely internet related. I try to handle cases for when links cannot be fetched the best I can, but it's not perfect.

If it takes a long time to start, it's because it's struggling to get the links. If you're internet is slow it's probably caused by that, if not I'm not sure, maybe cache? You can delete your cache in the settings (somewhere under formatting i think) but honestly I have no idea if that'd change anything

**Comment by DarkValkirion** [comment] 2020-12-19 03:27
I do not think it is a problem with my internet since in version 1.3.0 it worked perfect in 10.2, then update everything and when entering aio-switch-updater it began to give that behavior of errors and the strangest thing is that until I activate the airplane mode on the console was that it was able to open the updater. I don't know what it could be but I guess it's some problem on my console, anyway thanks for the help.

**Comment by HamletDuFromage** [comment] 2020-12-19 03:33
There's pretty much no difference 1.3.1 and 1.3.0 so it wouldn't make a difference 
Let me know if this persists

**Comment by DarkValkirion** [comment] 2020-12-21 01:12
Apparently I have fixed the "problem", I have been trying different situations to find out why this strange behavior happens and I have gotten to know a few things:
1. The problem is related to atmosphere. I tried to run aio in sx os and it works perfectly (it takes 2-3 seconds to show the screen, I used the same emummc and the same network connection so my internet connection is not the problem).
2. My internet connection is not the problem. By default it used 90dns, I tried to disable it and enable it and it still shows the same behavior in atmosphere.
3. I downgraded to firmware 10.2 and atmosphere 0.15.0 and it still shows the same behavior (previously this did not happen). This tells me that atmosphere or some component is interfering with the homebrew.
4. I did a formatting of my SD memory to fat32 (as I had it before) and I continue with the same problem.

Finally, I want to clarify that I tried the first point to the end, surprisingly when returning to atmosphere and running aio now it works normally, I don't know what sx os did but it seems to fix the problem of the "cache" or something that was kept in storage. I don't know if you could know where the problem is or if it is a problem unrelated to your homebrew.

**Comment by HamletDuFromage** [comment] 2020-12-29 00:37
Thank you for your help. I'm going to close this issue for now since I haven't got more reports like yours

**Comment by Enzemo** [comment] 2021-03-02 20:54
Hi sorry to reopen this but I'm getting the same issue. 11.0.1 AMS 0.16.2. OG switch, unpatched.

Hangs on a black screen, doesn't ever load any errors or do anything, Internet is working on other apps such as HbStore and YouTube. Doesn't freeze the switch. Tried launching from HB Details, HB Appstore, HB Launcher and from the NSP and all give the same result : nothing but an endless black screen. 

Enabling airplane mode does not change this behavior at all. I have deleted and downloaded the nca again but still doesn't resolve

**Comment by HamletDuFromage** [comment] 2021-03-02 23:41
That's a first... Could you try updating ams and reporting back?

**Comment by HamletDuFromage** [comment] 2021-03-10 19:57
Chances are you had some outdated sysmodules, that's usually the reason why HOS doesn't boot... I'm glad everything works for you now

**Comment by Enzemo** [comment] 2021-03-10 20:40
Another update for you, maybe needs it's own issue. After updating fully and using latest AIO files, it launches, but doesn't accept any inputs. I can return to the home menu but can't navigate within aio

**Closed** 2021-04-13 11:51 UTC
