### ISSUE TITLE
AIO Update on Mariko not handling stratosphere.romfs correctly, causing boot error with title ID 010041544d53000

### ISSUE THREAD

**Issue by IBNobody** [HamletDuFromage/aio-switch-updater#104] opened 2021-06-27 21:01 UTC
I used AIO 2.6.1 to update my Mariko Switch (running HOS 11) to Atmosphere 19.4 and Hekate 5.5.7 from Atmosphere 18.1 and Hekate 5.5.4.

After the update, Hekate boots fine, but Atmosphere crashes.

```
A fatal error occurred when running Atmosphere. Title ID: 010041544d53000
Error Desc: std :: abort () called (Oxffe)
```

I root-caused this issue down to Atmosphere 18.1 having the contents folder full of legacy Atmosphere sys-modules and AIO updater not properly handling the stratosphere.romfs correctly. Indeed, I found that stratosphere.romfs was still renamed stratosphere.romfs.aio. (EDIT: Thus, I suspect 19.4 was trying to use 18.1's old sys-modules.)

Once I renamed stratosphere.romfs.aio back to stratosphere.romfs, Atmosphere properly took care of fixing the contents folder and also using the correct sys-modules.

**Comment by HamletDuFromage** [comment] 2021-06-27 21:10
>I found that stratosphere.romfs was still renamed stratosphere.romfs.aio
That indeed would be the cause of the problem. What about `sept/payload.bin` and `atmosphere/fusee-secondary.bin` were/are they also respectively named `sept/payload.bin.aio` and `atmosphere/fusee-secondary.bin.aio`?

And when the console rebooted, did you see the text "Running aio-switch-updater rcm payload...\n" briefly popping up before the atmosphere/hekate bootscreen?. I'm trying to understand if the payload failed to rename that specific file, or if it was not ran altogether. By any chance you wouldn't be using exfat right?

**Comment by IBNobody** [comment] 2021-06-27 21:15
I saw yellow text that popped up briefly, but it was gone too fast before I could read it.

`atmosphere/fusee-secondary.bin` was properly renamed, and it also matched the hash in the Atmo distro. I didn't see any `atmosphere/fusee-secondary.bin.aio` artifact. I will check the sept folder as well, but I suspect that they are renamed correctly.

![image](https://user-images.githubusercontent.com/5863888/123559614-b77b2580-d762-11eb-856d-8aae23de0267.png)

**Comment by HamletDuFromage** [comment] 2021-06-27 21:30
Yellow text is good, which means the payload actually ran. The fact that it rebooted means the mariko specific code ran too. Now the fact that some files were renamed and some were not is quite odd, it's all in the same block https://github.com/HamletDuFromage/aiosu-rcm/blob/main/bootloader/main.c#L433-L443

I would check for corruption if I were you, this is quite unexpected, I believe on windows you can do it with chkdsk. For reboot_payload.bin not matching, it's also odd. You don't have a config/aio-switch-updater/copy_files.txt right? That could be causing it

**Comment by IBNobody** [comment] 2021-06-27 21:30
I'm on FAT32.

`sept` folders are identical.

I think some of my Hekate files are stale, though. `F:\bootloader\payloads\fusee-primary.bin` didn't match the CRC of the one I just downloaded. I'm not using this payload, though.

**Comment by IBNobody** [comment] 2021-06-27 21:49
Oh, after I looked at your code, I think I have an idea of why this failed. 

The bug is probably because pre-v19, stratosphere.romfs didn't exist. Thus, going from 18 to 19 causes the check for unlinking to fail, and thus, the rename never happens.

**Comment by HamletDuFromage** [comment] 2021-06-27 21:52
:^)
You would be right kek, what an oversight. Nice catch and thanks for pointing it out, I should have thought of that. That will be fixed in the next release

**Comment by IBNobody** [comment] 2021-06-27 21:58
Awesome. Glad I took the time to debug this rather than just re-blasting Atmosphere onto the SDCard.

And thanks again for all the hard work in getting Mariko updates working.

**Comment by HamletDuFromage** [comment] 2021-06-27 21:59
That's a big one though, that would cause crashes for all users going from sub 0.19 to 0.19+
Thanks a bunch

**Closed** 2021-06-27 22:47 UTC
